export const MOBILE_DEVICE_SEARCHING_START = "MOBILE_DEVICE_SEARCHING_START";
export const MOBILE_DEVICE_SEARCHING_STOP = "MOBILE_DEVICE_SEARCHING_STOP";
//
export const MOBILE_SIDEBAR_SLIDE_ON = "MOBILE_SIDEBAR_SLIDE_ON";
export const MOBILE_SIDEBAR_SLIDE_OFF = "MOBILE_SIDEBAR_SLIDE_OFF";
export const MOBILE_SIDEBAR_SLIDE_DEFAULT = "MOBILE_SIDEBAR_SLIDE_DEFAULT";
//
export const SEARCHING_START = "SEARCHING_START";
//
export const SAVE_DATA_FROM_BACKEND = "SAVE_DATA_FROM_BACKEND";

//
export const UPDATE_DATA = "UPDATE_DATA";

//
export const PAGE_NAVIGATOR = "PAGE_NAVIGATOR";
//
export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
